[package]
name = "cat_game"
version = "0.1.0"
edition = "2024"

[features]
debug = ["bevy-inspector-egui"]

[dependencies]
bevy = "0.16.0"
bevy-inspector-egui = {version = "0.31.0", optional = true}
serde = "1.0.219"
